### PR TITLE
CM-00 Project Initialization

### PR DESCRIPTION
**Pull request by merlindk**

### CODE REVIEW

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
QA Approved

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by FranciscodeMaussion** [comment]
@merlindk add to gitignore target/

**Pull request merged**
